# frozen_string_literal: true

require "test_helper"
require "git_support"
require_relative "../rakelib/commits"

class CommitPolicyTest < Minitest::Test
  include GitSupport

  TOOL_ADDRESSES = %w[noreply@anthropic.com codex@openai.com noreply@openai.com cursoragent@cursor.com
                      aider@aider.chat noreply@aider.chat copilot@github.com noreply@opencode.ai amp@ampcode.com
                      198982749+Copilot@users.noreply.github.com 218195315+gemini-cli@users.noreply.github.com
                      158243242+devin-ai-integration[bot]@users.noreply.github.com].freeze
  TOOL_NAMES = ["ChatGPT", "Claude Code", "Claude Code (Opus)", "Codex", "Copilot", "GitHub Copilot", "Cursor Agent",
                "Gemini", "Gemini CLI", "gemini-cli", "opencode"].freeze
  TOOL_LINES = [
    "Amp-Thread-ID: https://ampcode.com/threads/T-1", "Generated-by: a tool", "Assisted-by: Codex",
    "Generated with [Claude](https://example.org)", "Generated by Gemini CLI",
    "Details: https://claude.ai/code/session_01EXAMPLE0000000000000000",
    "https://chatgpt.com/codex/tasks/task_e_0123456789", "http://claude.ai/code/session_01EXAMPLE",
    "Session: claude.ai/code/session_01EXAMPLE", "<https://jules.google.com/task/1>"
  ].freeze
  HUMAN_LINES = [
    "Co-Authored-By: Claude Monet <claude@example.org>", "Co-authored-by: Gemini Santos <gemini.santos@example.org>",
    "Co-authored-by: Jules Verne <jules@example.org>", "Signed-off-by: Ada Lovelace <ada@openai.example.org>",
    "Generated with rake generate.", "Generated with cursor movement sequences.",
    "See https://claude.ai/ and https://chatgpt.com/ for the products.",
    "Reviewed-by: Cursor Maintainer <maintainer@example.org>", "See notclaude.ai/code/session_ for a lookalike."
  ].freeze

  def repository
    Dir.mktmpdir("rich-ri-commits-") do |root|
      git(root, "init", "-q")
      git(root, "commit", "--allow-empty", "-qm", "chore: initialize")
      yield root
    end
  end

  def lint(root, range = "HEAD", **env)
    Open3.capture3({ "PR_TITLE" => nil, "PR_BODY" => nil }.merge(env), RbConfig.ruby,
                   File.join(TestSupport::ROOT, "bin/lint-commits"), range, chdir: root)
  end

  def test_real_messages_separators_titles_and_human_coauthors
    repository do |root|
      git(root, "commit", "--allow-empty", "-qm",
          "fix: preserve documentation\n\nCo-Authored-By: Claude Monet <claude@example.org>")
      _out, err, status = lint(root, "HEAD", "PR_TITLE" => "fix: preserve documentation")

      assert_predicate status, :success?, err
      _out, err, status = lint(root, "HEAD", "PR_TITLE" => "An unstructured title")

      refute_predicate status, :success?
      assert_includes err, "lint-commits: PR title: use a Conventional Commit"
    end
  end

  def test_any_signature_with_the_address_of_a_tool_is_attribution
    trailers = %w[Co-authored-by Co-developed-by Signed-off-by Reviewed-by]
    signatures = TOOL_ADDRESSES.flat_map do |address|
      trailers.map { |trailer| "#{trailer}: Ada <#{address}>" }
    end

    assert_equal(signatures, signatures.select { |line| attributed?(line) })
  end

  def test_a_signature_with_the_name_of_a_tool_is_attribution
    signatures = TOOL_NAMES.map { |name| "Co-authored-by: #{name} <helper@example.org>" }

    assert_equal(signatures, signatures.select { |line| attributed?(line) })
  end

  def test_tool_trailers_generated_notes_and_session_links_are_attribution
    assert_equal(TOOL_LINES, TOOL_LINES.select { |line| attributed?(line) })
  end

  def test_people_and_plain_references_are_not_attribution
    assert_empty(HUMAN_LINES.select { |line| attributed?(line) })
  end

  def test_the_offending_line_is_quoted_without_its_indentation
    assert_equal ["remove generated attribution: Assisted-by: Codex"],
                 CommitPolicy.check("Fix it.\n\n  Assisted-by: Codex  \nMore text.", subject: false)
  end

  def test_attribution_in_commits_and_pr_bodies_is_rejected_with_the_offending_line
    repository do |root|
      body = "Fix completion.\n\nhttps://claude.ai/code/session_01EXAMPLE0000000000000000"
      _out, err, status = lint(root, "HEAD", "PR_BODY" => body)

      refute_predicate status, :success?
      assert_equal "lint-commits: PR body: remove generated attribution: https://claude.ai/code/session_01EXAMPLE0000000000000000\n",
                   err
      git(root, "commit", "--allow-empty", "-qm", "fix: correct rendering\n\nGenerated-with: Codex")
      _out, err, status = lint(root)

      refute_predicate status, :success?
      assert_match(/\Alint-commits: \h{8}: remove generated attribution: Generated-with: Codex\n\z/, err)
    end
  end

  def test_unfinished_subjects_are_rejected_and_git_reverts_are_accepted
    unfinished = ["fix: wip", "fix: WIP still broken", "fix(cli): wip", "WIP", "wip: try things",
                  "fixup! fix: preserve documentation", "squash! fix: preserve documentation",
                  "amend! fix: preserve documentation", 'Revert "fixup! fix: preserve documentation"']
    accepted = ["fix: wipe stale caches", "fix: WIP-free path", 'Revert "fix: preserve documentation"',
                'Reapply "fix: preserve documentation"', 'Revert "Revert "fix: preserve documentation""',
                "revert: restore the previous pager default", "chore(deps): bump rdoc from 8.1.0 to 8.2.0"]

    assert_equal(unfinished, (unfinished + accepted).select do |subject|
      CommitPolicy.check(subject, subject: true).grep(/\Afinish this commit first/).any?
    end)
    assert_empty(accepted.flat_map { |subject| CommitPolicy.check(subject, subject: true) })
    assert_match(/\Ause a Conventional Commit subject, "type\(scope\): summary" with one of feat, fix, .+: Revert it\z/,
                 CommitPolicy.check('Revert "Revert it"', subject: true).first)
  end

  def test_shallow_merge_uses_stored_parents_but_still_checks_its_body
    repository do |root|
      git(root, "switch", "-qc", "topic")
      git(root, "commit", "--allow-empty", "-qm", "fix: improve completion")
      git(root, "switch", "-q", "main")
      git(root, "commit", "--allow-empty", "-qm", "docs: explain completion")
      git(root, "merge", "--no-ff", "topic", "-m", "Merge synthetic PR")
      Dir.mktmpdir("rich-ri-shallow-") do |clone|
        git(root, "clone", "-q", "--depth=1", "file://#{root}", clone)
        _out, err, status = lint(clone)

        assert_predicate status, :success?, err
      end
      git(root, "commit", "--amend", "-qm", "Merge synthetic PR\n\nGenerated-by: Codex")
      _out, err, status = lint(root)

      refute_predicate status, :success?
      assert_includes err, "remove generated attribution"
    end
  end

  def test_an_unstructured_subject_names_the_accepted_form
    repository do |root|
      git(root, "commit", "--allow-empty", "-qm", "unstructured commit")
      sha = git(root, "rev-parse", "--short=8", "HEAD")
      _out, err, status = lint(root)

      assert_equal 1, status.exitstatus
      assert_equal "lint-commits: #{sha}: use a Conventional Commit subject, \"type(scope): summary\" with one of " \
                   "feat, fix, docs, test, refactor, perf, build, ci, chore, revert: unstructured commit\n", err
    end
  end

  def test_a_range_git_cannot_read_carries_the_reason_git_gives
    repository do |root|
      _out, err, status = lint(root, "missing..HEAD")

      assert_equal 1, status.exitstatus
      assert_equal "lint-commits: cannot read commits: fatal: bad revision 'missing..HEAD'\n", err
    end
  end

  def test_control_characters_from_commits_and_pull_requests_are_shown_as_text
    repository do |root|
      git(root, "commit", "--allow-empty", "-qm", "\e]0;renamed\a\e[31mred")
      sha = git(root, "rev-parse", "--short=8", "HEAD")
      _out, err, status = lint(root, "PR_BODY" => "Notes\n\nhttps://claude.ai/code/session_1 \e[2J")

      assert_equal 1, status.exitstatus
      assert_equal "lint-commits: #{sha}: use a Conventional Commit subject, \"type(scope): summary\" with one of " \
                   "feat, fix, docs, test, refactor, perf, build, ci, chore, revert: \\e]0;renamed\\a\\e[31mred\n" \
                   "lint-commits: PR body: remove generated attribution: https://claude.ai/code/session_1 \\e[2J\n",
                   err
    end
  end

  private

  def attributed?(line) = CommitPolicy.check("Fix it.\n\n#{line}\n", subject: false).any?
end
