# frozen_string_literal: true

require "test_helper"
require "commit_support"
require_relative "../rakelib/commits"

class CommitPolicyTest < Minitest::Test
  include CommitSupport

  UNSTRUCTURED = 'use a Conventional Commit subject, "type(scope): summary" with one of feat, fix, docs, test, ' \
                 "refactor, perf, build, ci, chore, revert: "
  TOOL_ADDRESSES = %w[noreply@anthropic.com codex@openai.com noreply@openai.com cursoragent@cursor.com
                      aider@aider.chat noreply@aider.chat copilot@github.com noreply@opencode.ai amp@ampcode.com
                      198982749+Copilot@users.noreply.github.com 218195315+gemini-cli@users.noreply.github.com
                      158243242+devin-ai-integration[bot]@users.noreply.github.com].freeze
  TOOL_NAMES = ["ChatGPT", "Claude Code", "Claude Code (Opus)", "Codex", "Copilot", "GitHub Copilot", "Cursor Agent",
                "Gemini", "Gemini CLI", "gemini-cli", "opencode"].freeze
  TOOL_LINES = [
    "Amp-Thread-ID: https://ampcode.com/threads/T-1", "Generated-by: a tool", "Assisted-by: Codex",
    "Generated with [Claude](https://example.org)", "Generated by Gemini CLI",
    "Details: https://claude.ai/code/session_01EXAMPLE0000000000000000",
    "https://chatgpt.com/codex/tasks/task_e_0123456789", "http://claude.ai/code/session_01EXAMPLE",
    "Session: claude.ai/code/session_01EXAMPLE", "<https://jules.google.com/task/1>"
  ].freeze
  HUMAN_LINES = [
    "Co-Authored-By: Claude Monet <claude@example.org>", "Co-authored-by: Gemini Santos <gemini.santos@example.org>",
    "Co-authored-by: Jules Verne <jules@example.org>", "Signed-off-by: Ada Lovelace <ada@openai.example.org>",
    "Generated with rake generate.", "Generated with cursor movement sequences.",
    "See https://claude.ai/ and https://chatgpt.com/ for the products.",
    "Reviewed-by: Cursor Maintainer <maintainer@example.org>", "See notclaude.ai/code/session_ for a lookalike."
  ].freeze

  def teardown
    FileUtils.remove_entry(@policy_root) if @policy_root
  end

  def test_a_conventional_commit_with_a_human_coauthor_and_title_passes
    repository do |root|
      git(root, "commit", "--allow-empty", "-qm",
          "fix: preserve documentation\n\nCo-Authored-By: Claude Monet <claude@example.org>")
      _out, err, status = lint(root, "HEAD", "PR_TITLE" => "fix: preserve documentation")

      assert_equal [0, ""], [status.exitstatus, err]
    end
  end

  def test_an_unstructured_pull_request_title_is_rejected
    repository do |root|
      _out, err, status = lint(root, "HEAD", "PR_TITLE" => "An unstructured title")

      assert_equal [1, "lint-commits: pull request title: #{UNSTRUCTURED}An unstructured title\n"],
                   [status.exitstatus, err]
    end
  end

  def test_any_signature_with_the_address_of_a_tool_is_attribution
    trailers = %w[Co-authored-by Co-developed-by Signed-off-by Reviewed-by]
    signatures = TOOL_ADDRESSES.flat_map do |address|
      trailers.map { |trailer| "#{trailer}: Ada <#{address}>" }
    end

    assert_equal(signatures, signatures.select { |line| attributed?(line) })
  end

  def test_a_signature_with_the_name_of_a_tool_is_attribution
    signatures = TOOL_NAMES.map { |name| "Co-authored-by: #{name} <helper@example.org>" }

    assert_equal(signatures, signatures.select { |line| attributed?(line) })
  end

  def test_tool_trailers_generated_notes_and_session_links_are_attribution
    assert_equal(TOOL_LINES, TOOL_LINES.select { |line| attributed?(line) })
  end

  def test_people_and_plain_references_are_not_attribution
    assert_empty(HUMAN_LINES.select { |line| attributed?(line) })
  end

  def test_the_offending_line_is_quoted_without_its_indentation
    assert_equal ["pull request body: remove generated attribution: Assisted-by: Codex"],
                 pull_request_problems(body: "Fix it.\n\n  Assisted-by: Codex  \nMore text.")
  end

  def test_attribution_in_a_pull_request_body_is_rejected_with_the_offending_line
    repository do |root|
      body = "Fix completion.\n\nhttps://claude.ai/code/session_01EXAMPLE0000000000000000"
      _out, err, status = lint(root, "HEAD", "PR_BODY" => body)

      assert_equal [1, "lint-commits: pull request body: remove generated attribution: " \
                       "https://claude.ai/code/session_01EXAMPLE0000000000000000\n"], [status.exitstatus, err]
    end
  end

  def test_attribution_in_a_commit_is_rejected_with_the_offending_line
    repository do |root|
      git(root, "commit", "--allow-empty", "-qm", "fix: correct rendering\n\nGenerated-with: Codex")
      sha = git(root, "rev-parse", "--short=8", "HEAD")
      _out, err, status = lint(root)

      assert_equal [1, "lint-commits: #{sha}: remove generated attribution: Generated-with: Codex\n"],
                   [status.exitstatus, err]
    end
  end

  def test_unfinished_subjects_are_rejected
    unfinished = ["fix: wip", "fix: WIP still broken", "fix(cli): wip", "WIP", "wip: try things",
                  "fixup! fix: preserve documentation", "squash! fix: preserve documentation",
                  "amend! fix: preserve documentation"].to_h { |subject| [subject, subject] }
    unfinished['Revert "fixup! fix: preserve documentation"'] = "fixup! fix: preserve documentation"

    unfinished.each do |subject, quoted|
      assert_equal ["pull request title: finish this commit first; fixup!, squash!, amend! and WIP subjects are not " \
                    "accepted: #{quoted}"], pull_request_problems(title: subject)
    end
  end

  def test_reverts_of_conventional_subjects_are_accepted
    accepted = ['Revert "fix: preserve documentation"', 'Reapply "fix: preserve documentation"',
                'Revert "Revert "fix: preserve documentation""', "revert: restore the previous pager default"]

    assert_empty(accepted.flat_map { |subject| pull_request_problems(title: subject) })
  end

  def test_words_that_start_with_wip_are_not_unfinished_work
    accepted = ["fix: wipe stale caches", "fix: WIP-free path"]

    assert_empty(accepted.flat_map { |subject| pull_request_problems(title: subject) })
  end

  def test_a_scoped_dependency_update_is_accepted
    assert_empty pull_request_problems(title: "chore(deps): bump rdoc from 8.1.0 to 8.2.0")
  end

  def test_a_revert_of_an_unstructured_subject_is_still_unstructured
    assert_equal ["pull request title: #{UNSTRUCTURED}Revert it"], pull_request_problems(title: 'Revert "Revert it"')
  end

  def test_shallow_merge_uses_stored_parents_but_still_checks_its_body
    repository do |root|
      git(root, "switch", "-qc", "topic")
      git(root, "commit", "--allow-empty", "-qm", "fix: improve completion")
      git(root, "switch", "-q", "main")
      git(root, "commit", "--allow-empty", "-qm", "docs: explain completion")
      git(root, "merge", "--no-ff", "topic", "-m", "Merge synthetic PR")
      Dir.mktmpdir("rich-ri-shallow-") do |clone|
        git(root, "clone", "-q", "--depth=1", "file://#{root}", clone)
        _out, err, status = lint(clone)

        assert_predicate status, :success?, err
      end
      git(root, "commit", "--amend", "-qm", "Merge synthetic PR\n\nGenerated-by: Codex")
      sha = git(root, "rev-parse", "--short=8", "HEAD")
      _out, err, status = lint(root)

      assert_equal [1, "lint-commits: #{sha}: remove generated attribution: Generated-by: Codex\n"],
                   [status.exitstatus, err]
    end
  end

  def test_an_unstructured_subject_names_the_accepted_form
    repository do |root|
      git(root, "commit", "--allow-empty", "-qm", "unstructured commit")
      sha = git(root, "rev-parse", "--short=8", "HEAD")
      _out, err, status = lint(root)

      assert_equal 1, status.exitstatus
      assert_equal "lint-commits: #{sha}: #{UNSTRUCTURED}unstructured commit\n", err
    end
  end

  def test_a_range_git_cannot_read_carries_the_reason_git_gives
    repository do |root|
      _out, err, status = lint(root, "missing..HEAD")

      assert_equal 1, status.exitstatus
      assert_equal "lint-commits: cannot read commits: fatal: bad revision 'missing..HEAD'\n", err
    end
  end

  def test_an_error_git_writes_on_several_lines_keeps_its_lines
    repository do |root|
      parent = git(root, "rev-parse", "HEAD")
      git(root, "commit", "--allow-empty", "-qm", "fix: correct rendering")
      head = git(root, "rev-parse", "HEAD")
      File.delete(File.join(root, ".git/objects", parent[0, 2], parent[2..]))
      _out, err, status = lint(root)

      assert_equal [1, "lint-commits: cannot read commits: error: Could not read #{parent}\n" \
                       "fatal: Failed to traverse parents of commit #{head}\n"], [status.exitstatus, err]
    end
  end

  def test_control_characters_from_commits_and_pull_requests_are_shown_as_text
    repository do |root|
      git(root, "commit", "--allow-empty", "-qm", "\e]0;renamed\a\e[31mred")
      sha = git(root, "rev-parse", "--short=8", "HEAD")
      _out, err, status = lint(root, "PR_BODY" => "Notes\n\nhttps://claude.ai/code/session_1 \e[2J")

      assert_equal 1, status.exitstatus
      assert_equal "lint-commits: #{sha}: #{UNSTRUCTURED}\\e]0;renamed\\a\\e[31mred\n" \
                   "lint-commits: pull request body: remove generated attribution: " \
                   "https://claude.ai/code/session_1 \\e[2J\n",
                   err
    end
  end

  private

  def attributed?(line) = pull_request_problems(body: "Fix it.\n\n#{line}\n").any?

  # An empty range leaves only the pull request title or body to check.
  def pull_request_problems(**text)
    @policy_root ||= Dir.mktmpdir("rich-ri-policy-").tap do |root|
      git(root, "init", "-q")
      git(root, "commit", "--allow-empty", "-qm", "chore: initialize")
    end
    Dir.chdir(@policy_root) { CommitPolicy.problems("HEAD..HEAD", **text) }
  end
end
