# frozen_string_literal: true

require "test_helper"
require "git_support"
require_relative "../rakelib/commits"

class CommitPolicyTest < Minitest::Test
  include GitSupport

  TOOL_LINES = [
    "Co-Authored-By: Claude <noreply@anthropic.com>", "Co-authored-by: Codex <codex@openai.com>",
    "Co-authored-by: Codex <noreply@openai.com>", "Co-authored-by: Gemini <gemini@example.org>",
    "Co-authored-by: gemini-cli <218195315+gemini-cli@users.noreply.github.com>",
    "Co-authored-by: GitHub Copilot <copilot@github.com>",
    "Co-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>",
    "Co-authored-by: aider (gpt-5) <aider@aider.chat>", "Signed-off-by: Cursor Agent <cursoragent@cursor.com>",
    "Co-authored-by: opencode <noreply@opencode.ai>", "Amp-Thread-ID: https://ampcode.com/threads/T-1",
    "Generated-by: a tool", "Assisted-by: Codex", "Generated with [Claude](https://example.org)",
    "Generated by Gemini CLI", "Details: https://claude.ai/code/session_01EXAMPLE0000000000000000",
    "https://chatgpt.com/codex/tasks/task_e_0123456789"
  ].freeze
  HUMAN_LINES = [
    "Co-Authored-By: Claude Monet <claude@example.org>", "Co-authored-by: Gemini Santos <gemini.santos@example.org>",
    "Co-authored-by: Jules Verne <jules@example.org>", "Signed-off-by: Ada Lovelace <ada@openai.example.org>",
    "Generated with rake generate.", "Generated with cursor movement sequences.",
    "See https://claude.ai/ and https://chatgpt.com/ for the products.",
    "Reviewed-by: Cursor Maintainer <maintainer@example.org>"
  ].freeze

  def repository
    Dir.mktmpdir("rich-ri-commits-") do |root|
      git(root, "init", "-q")
      git(root, "commit", "--allow-empty", "-qm", "chore: initialize")
      yield root
    end
  end

  def lint(root, range = "HEAD", **env)
    Open3.capture3({ "PR_TITLE" => nil, "PR_BODY" => nil }.merge(env), RbConfig.ruby,
                   File.join(TestSupport::ROOT, "bin/lint-commits"), range, chdir: root)
  end

  def test_real_messages_separators_titles_and_human_coauthors
    repository do |root|
      git(root, "commit", "--allow-empty", "-qm",
          "fix: preserve documentation\n\nCo-Authored-By: Claude Monet <claude@example.org>")
      _out, err, status = lint(root, "HEAD", "PR_TITLE" => "fix: preserve documentation")

      assert_predicate status, :success?, err
      _out, err, status = lint(root, "HEAD", "PR_TITLE" => "An unstructured title")

      refute_predicate status, :success?
      assert_includes err, "PR title: Use a Conventional Commit"
    end
  end

  def test_lines_written_by_tools_are_told_from_people_and_plain_references
    credited = (TOOL_LINES + HUMAN_LINES).select { |line| CommitPolicy.attribution("Fix it.\n\n#{line}\n") }

    assert_equal TOOL_LINES, credited
    assert_equal "Assisted-by: Codex", CommitPolicy.attribution("Fix it.\n\n  Assisted-by: Codex  \nMore text.")
  end

  def test_attribution_in_commits_and_pr_bodies_is_rejected_with_the_offending_line
    repository do |root|
      body = "Fix completion.\n\nhttps://claude.ai/code/session_01EXAMPLE0000000000000000"
      _out, err, status = lint(root, "HEAD", "PR_BODY" => body)

      refute_predicate status, :success?
      assert_equal "PR body: Remove generated attribution: https://claude.ai/code/session_01EXAMPLE0000000000000000\n",
                   err
      git(root, "commit", "--allow-empty", "-qm", "fix: correct rendering\n\nGenerated-with: Codex")
      _out, err, status = lint(root)

      refute_predicate status, :success?
      assert_match(/\A\h{8}: Remove generated attribution: Generated-with: Codex\n\z/, err)
    end
  end

  def test_unfinished_subjects_are_rejected_and_git_reverts_are_accepted
    unfinished = ["fix: wip", "fix: WIP still broken", "fix(cli): wip", "WIP", "wip: try things",
                  "fixup! fix: preserve documentation", "squash! fix: preserve documentation",
                  "amend! fix: preserve documentation", 'Revert "fixup! fix: preserve documentation"']
    accepted = ["fix: wipe stale caches", 'Revert "fix: preserve documentation"',
                'Reapply "fix: preserve documentation"', 'Revert "Revert "fix: preserve documentation""',
                "revert: restore the previous pager default", "chore(deps): bump rdoc from 8.1.0 to 8.2.0"]

    assert_equal(unfinished, (unfinished + accepted).select do |subject|
      CommitPolicy.check(subject, subject: true).grep(/\AFinish this commit first/).any?
    end)
    assert_empty(accepted.flat_map { |subject| CommitPolicy.check(subject, subject: true) })
    assert_match(/\AUse a Conventional Commit subject, "type\(scope\): summary" with one of feat, fix, .+: Revert it\z/,
                 CommitPolicy.check('Revert "Revert it"', subject: true).first)
  end

  def test_shallow_merge_uses_stored_parents_but_still_checks_its_body
    repository do |root|
      git(root, "switch", "-qc", "topic")
      git(root, "commit", "--allow-empty", "-qm", "fix: improve completion")
      git(root, "switch", "-q", "main")
      git(root, "commit", "--allow-empty", "-qm", "docs: explain completion")
      git(root, "merge", "--no-ff", "topic", "-m", "Merge synthetic PR")
      Dir.mktmpdir("rich-ri-shallow-") do |clone|
        git(root, "clone", "-q", "--depth=1", "file://#{root}", clone)
        _out, err, status = lint(clone)

        assert_predicate status, :success?, err
      end
      git(root, "commit", "--amend", "-qm", "Merge synthetic PR\n\nGenerated-by: Codex")
      _out, err, status = lint(root)

      refute_predicate status, :success?
      assert_includes err, "Remove generated attribution"
    end
  end

  def test_invalid_subject_and_range_fail_with_actionable_messages
    repository do |root|
      git(root, "commit", "--allow-empty", "-qm", "unstructured commit")
      _out, err, status = lint(root)

      refute_predicate status, :success?
      assert_includes err, "Use a Conventional Commit"
      _out, err, status = lint(root, "missing..HEAD")

      refute_predicate status, :success?
      assert_includes err, "Cannot read commits"
    end
  end
end
