# frozen_string_literal: true

require "rdoc/ri/driver"
require "prism"
require "reline"
require "io/console"
require "open3"
require "shellwords"
require "timeout"
require "psych"

require_relative "rich_ri/version"
require_relative "rich_ri/errors"
require_relative "rich_ri/ansi"
require_relative "rich_ri/theme"
require_relative "rich_ri/configuration_file"
require_relative "rich_ri/configuration"
require_relative "rich_ri/configuration_options"
require_relative "rich_ri/bat"
require_relative "rich_ri/highlighter"
require_relative "rich_ri/formatter"
require_relative "rich_ri/store"
require_relative "rich_ri/driver"
require_relative "rich_ri/options"
require_relative "rich_ri/completion"
require_relative "rich_ri/cli"
